AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: CD Demo Lambda
Resources:
  IndexPhotosLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: index-photos-cd
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: ./LambdaCode/LF1/lambda_function.py
      Description: 'Index photos function'
      MemorySize: 128
      Timeout: 30
      Layers:
        - 'arn:aws:lambda:us-east-1:232083808386:layer:requests:2'
      Role: 'arn:aws:iam::232083808386:role/service-role/indexPhotosRole'
#      Events:
#        getAZsAPI:
#          Type: Api
#          Properties:
#            Path: /getazs
#            Method: get
      Environment:
        Variables:
          REGION: us-east-1
      VpcConfig:
        SecurityGroupIds:
          - sg-9c472db5
        SubnetIds:
          - subnet-ec51438b

  IndexPhotosLambdaS3Permission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: 'lambda:InvokeFunction'
#      EventSourceToken: String
      FunctionName: !GetAtt IndexPhotosLambda.Arn
      Principal: 's3.amazonaws.com'
#      SourceAccount: String
      SourceArn: 'arn:aws:s3:::ass3-b2-cd'


  SearchPhotosLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: search-photos-cd
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: ./LambdaCode/LF2/lambda_function.py
      Description: 'Search photos function'
      MemorySize: 128
      Timeout: 30
      Layers:
        - 'arn:aws:lambda:us-east-1:232083808386:layer:elasticsearch:2'
      Role: 'arn:aws:iam::232083808386:role/service-role/Search-photos-role'
      # Events:
      #   APIPhotoAlbum:
      #     Type: Api
      #     Properties:
      #       Path: /search
      #       Method: get
      Environment:
        Variables:
          REGION: us-east-1
      VpcConfig:
        SecurityGroupIds:
          - sg-9c472db5
        SubnetIds:
          - subnet-ec51438b

  ConfigLambdaPermission:
    Type: "AWS::Lambda::Permission"
    DependsOn:
      - APIAss3
      - SearchPhotosLambda
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref SearchPhotosLambda
      Principal: apigateway.amazonaws.com

  PhotosES:
    Type: AWS::Elasticsearch::Domain
    Properties:
      DomainName: photos-cd
      ElasticsearchVersion: '7.4'
      ElasticsearchClusterConfig:
        DedicatedMasterEnabled: false
        InstanceCount: 1
        ZoneAwarenessEnabled: false
        InstanceType: 'r5.large.elasticsearch'
      EBSOptions:
        EBSEnabled: true
        VolumeSize: 10
        VolumeType: 'gp2'
      VPCOptions:
        SecurityGroupIds:
          - sg-9c472db5
        SubnetIds:
          - subnet-ec51438b

  PhotoBucketS3:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: ass3-b2-cd
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: 's3:ObjectCreated:Put'
            Function: !GetAtt IndexPhotosLambda.Arn
#            Function: 'arn:aws:lambda:us-east-1:232083808386:function:index-photos-cd'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      WebsiteConfiguration:
        ErrorDocument: 'error.html'
        IndexDocument: 'index.html'
#
  PhotoBucketS3Policy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref PhotoBucketS3
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: AWSRekognitionS3AclBucketRead20191011
            Effect: Allow
            Principal:
              Service: rekognition.amazonaws.com
            Action:
              - 's3:GetBucketAcl'
              - 's3:GetBucketLocation'
#            Resource: 'arn:aws:s3:::ass3-b2-cd'
            Resource: !GetAtt PhotoBucketS3.Arn
          - Sid: AWSRekognitionS3GetBucket20191011
            Effect: Allow
            Principal:
              Service: rekognition.amazonaws.com
            Action:
              - 's3:GetObject'
              - 's3:GetObjectAcl'
              - 's3:GetObjectVersion'
              - 's3:GetObjectTagging'
#            Resource: 'arn:aws:s3:::ass3-b2-cd/*'
            Resource: !Join [ "/", [ !GetAtt PhotoBucketS3.Arn, '*']]
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
#            Resource: 'arn:aws:s3:::ass3-b2-cd/*'
            Resource: !Join [ "/", [ !GetAtt PhotoBucketS3.Arn, '*']]

  APIAss3:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Description: 'API for assignment 3 for Cloud Computing and Big Data course'
      EndpointConfiguration:
        Types: 
          - REGIONAL
      Name: 'APIAss3'
      Body:
        openapi: "3.0.1"
        info:
          title: "APIAss3"
          description: "AI Photo Search application, built during the Cloud and Big Data course at Columbia University."
          version: "1.0.0"
        servers:
        - url: "https://ioepn8ggz8.execute-api.us-east-1.amazonaws.com/{basePath}"
          variables:
            basePath:
              default: "/beta"
        paths:
          /search:
            get:
              operationId: "searchPhotos"
              parameters:
              - name: "q"
                in: "query"
                schema:
                  type: "string"
              responses:
                '500':
                  description: "500 response"
                  content:
                    application/json:
                      schema:
                        $ref: "#/components/schemas/Error"
                '200':
                  description: "200 response"
                  headers:
                    Access-Control-Allow-Origin:
                      schema:
                        type: "string"
                  content:
                    application/json:
                      schema:
                        $ref: "#/components/schemas/SearchResponse"
                '403':
                  description: "403 response"
                  content:
                    application/json:
                      schema:
                        $ref: "#/components/schemas/Error"
              x-amazon-apigateway-integration:
                uri: "arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/${SearchPhotosLambda.Arn}/invocations"
                responses:
                  default:
                    statusCode: "200"
                    responseParameters:
                      method.response.header.Access-Control-Allow-Origin: "'*'"
                requestTemplates:
                  application/json: "{\n    \"query\": \"$input.params('q')\"\n}"
                passthroughBehavior: "when_no_templates"
                httpMethod: "POST"
                contentHandling: "CONVERT_TO_TEXT"
                type: "aws"
            options:
              responses:
                '500':
                  description: "500 response"
                  content: {}
                '200':
                  description: "200 response"
                  headers:
                    Access-Control-Allow-Origin:
                      schema:
                        type: "string"
                    Access-Control-Allow-Methods:
                      schema:
                        type: "string"
                    Access-Control-Allow-Headers:
                      schema:
                        type: "string"
                  content: {}
                '403':
                  description: "403 response"
                  content: {}
              x-amazon-apigateway-integration:
                responses:
                  default:
                    statusCode: "200"
                    responseParameters:
                      method.response.header.Access-Control-Allow-Methods: "'GET,OPTIONS'"
                      method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
                      method.response.header.Access-Control-Allow-Origin: "'*'"
                requestTemplates:
                  application/json: "{\"statusCode\": 200}"
                passthroughBehavior: "when_no_match"
                type: "mock"
        components:
          schemas:
            Empty:
              $schema: 'http://json-schema.org/draft-04/schema#'
              title : 'Empty Schema'
              type : 'object'
            Error:
              type: "object"
              properties:
                code:
                  type: "integer"
                  format: "int32"
                message:
                  type: "string"
            Photo:
              type: "object"
              properties:
                url:
                  type: "string"
                labels:
                  type: "array"
                  items:
                    type: "string"
            SearchResponse:
              type: "object"
              properties:
                results:
                  type: "array"
                  items:
                    $ref: "#/components/schemas/Photo"
        x-amazon-apigateway-gateway-responses:
          DEFAULT_4XX:
            responseParameters:
              gatewayresponse.header.Access-Control-Allow-Methods: "'OPTIONS,PUT'"
              gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
              gatewayresponse.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
          DEFAULT_5XX:
            responseParameters:
              gatewayresponse.header.Access-Control-Allow-Methods: "'OPTIONS,PUT'"
              gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
              gatewayresponse.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        x-amazon-apigateway-binary-media-types:
        - "image/jpeg"

  APIDeployment:
    Type: AWS::ApiGateway::Deployment
    Properties:
      Description: Lambda API Deployment
      RestApiId: !Ref APIAss3
      StageName: 'beta'


#        {
#          "Version": "2012-10-17",
#          "Statement": [
#          {
#            "Sid": "AWSRekognitionS3AclBucketRead20191011",
#            "Effect": "Allow",
#            "Principal": {
#              "Service": "rekognition.amazonaws.com"
#            },
#            "Action": [
#              "s3:GetBucketAcl",
#              "s3:GetBucketLocation"
#            ],
##            "Resource": "arn:aws:s3:::ass3-b2-cd"
##            "Resource": !Join [ "/", [ !GetAtt PhotoBucketS3.Arn, '*']]
#            "Resource": "arn:aws:s3:::ass3-b2-cd/*"
#          },
#          {
#            "Sid": "AWSRekognitionS3GetBucket20191011",
#            "Effect": "Allow",
#            "Principal": {
#              "Service": "rekognition.amazonaws.com"
#            },
#            "Action": [
#              "s3:GetObject",
#              "s3:GetObjectAcl",
#              "s3:GetObjectVersion",
#              "s3:GetObjectTagging"
#            ],
##            "Resource": "arn:aws:s3:::ass3-b2/*"
#            "Resource": "arn:aws:s3:::ass3-b2-cd/*"
##            "Resource": !GetAtt PhotoBucketS3.Arn
##            "Resource": !Join [ "/", [ !GetAtt PhotoBucketS3.Arn, '*']]
#          },
#          {
#            "Sid": "PublicReadGetObject",
#            "Effect": "Allow",
#            "Principal": "*",
#            "Action": "s3:GetObject",
#            "Resource": "arn:aws:s3:::ass3-b2-cd/*"
##            "Resource": !GetAtt PhotoBucketS3.Arn
##            "Resource": !Join [ "/", [ !GetAtt PhotoBucketS3.Arn, '*']]
#          }
#          ]
#        }

  # link to lambda on put
  # public access DONE
  # Bucket policy DONE


